# Generated by Django 6.0.4 on 2026-04-28 14:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(help_text='Унікальний ідентифікатор для URL (тільки латиниця, цифри, дефіси)', max_length=255, unique=True, verbose_name='Слаг (URL)')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Назва')),
                ('brand', models.CharField(db_index=True, max_length=255, verbose_name='Бренд')),
                ('description', models.TextField(blank=True, default='', verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Ціна (грн)')),
                ('volume', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name="Об'єм (мл)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand', 'name'], name='idx_product_brand_name'), models.Index(fields=['price'], name='idx_product_price'), models.Index(fields=['-created_at'], name='idx_product_created')],
            },
        ),
    ]
