# Generated by Django 6.0.4 on 2026-05-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fragrance_group',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Група ароматів'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Чоловічі'), ('F', 'Жіночі'), ('U', 'Унісекс')], default='U', max_length=1, verbose_name='Стать'),
        ),
    ]
